<?
$PERM["lists"]["2"]="X";
$PERM["lists"]["3"]="X";
$PERM["lists"]["12"]="X";
$PERM["lists"]["4"]="X";
$PERM["lists"]["9"]="X";
$PERM["lists"]["10"]="X";
$PERM["lists"]["13"]="X";
$PERM["lists"]["6"]="X";
$PERM["lists"]["8"]="X";
$PERM["lists"]["11"]="X";
$PERM["lists"]["16"]="X";
$PERM["lists"]["7"]="X";
$PERM["lists"]["14"]="X";
$PERM["lists"]["15"]="X";
$PERM["lists"]["17"]="X";
$PERM["lists"]["18"]="X";
$PERM["lists"]["5"]="X";
?>